name: folego
description: Fôlego — quanto você realmente pode gastar hoje sem apertar amanhã.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: any
  supabase_flutter: ^2.17.2
  google_fonts: ^8.2.1
  tabler_icons_plus: ^3.46.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true