alter table public.notification_preferences
  add column if not exists daily_summary_enabled boolean not null default true,
  add column if not exists daily_summary_time time not null default '09:00:00',
  add column if not exists quiet_hours_enabled boolean not null default true,
  add column if not exists quiet_hours_start time not null default '22:00:00',
  add column if not exists quiet_hours_end time not null default '08:00:00';

create table if not exists public.notification_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  space_id uuid not null references public.financial_spaces(id) on delete cascade,
  stable_key text not null,
  kind text not null,
  title text not null,
  body text not null,
  route text not null default '/',
  delivered_at timestamptz not null default now(),
  constraint notification_history_user_stable_key unique (user_id, stable_key)
);

create index if not exists notification_history_user_space_delivered_idx
  on public.notification_history (user_id, space_id, delivered_at desc);
create index if not exists notification_history_space_id_idx
  on public.notification_history (space_id);
create index if not exists web_push_delivery_log_space_id_idx
  on public.web_push_delivery_log (space_id);

alter table public.notification_history enable row level security;
revoke all on public.notification_history from anon, authenticated;
grant select on public.notification_history to authenticated;

drop policy if exists notification_history_select_own on public.notification_history;
create policy notification_history_select_own
on public.notification_history for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists sheet_sync_integrations_no_client_access on public.sheet_sync_integrations;
create policy sheet_sync_integrations_no_client_access
on public.sheet_sync_integrations for all
to authenticated
using (false)
with check (false);

drop policy if exists web_push_subscriptions_select_own on public.web_push_subscriptions;
create policy web_push_subscriptions_select_own
on public.web_push_subscriptions for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists web_push_subscriptions_insert_own on public.web_push_subscriptions;
create policy web_push_subscriptions_insert_own
on public.web_push_subscriptions for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists web_push_subscriptions_update_own on public.web_push_subscriptions;
create policy web_push_subscriptions_update_own
on public.web_push_subscriptions for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists web_push_subscriptions_delete_own on public.web_push_subscriptions;
create policy web_push_subscriptions_delete_own
on public.web_push_subscriptions for delete
to authenticated
using ((select auth.uid()) = user_id);

create or replace function private.is_web_push_quiet(
  p_now timestamptz,
  p_timezone text,
  p_enabled boolean,
  p_start time,
  p_end time
)
returns boolean
language plpgsql
stable
set search_path = ''
as $$
declare
  local_time time;
begin
  if not coalesce(p_enabled, false) then return false; end if;
  local_time := (p_now at time zone p_timezone)::time;
  if p_start = p_end then return false; end if;
  if p_start < p_end then
    return local_time >= p_start and local_time < p_end;
  end if;
  return local_time >= p_start or local_time < p_end;
end;
$$;

revoke all on function private.is_web_push_quiet(timestamptz,text,boolean,time,time) from public, anon, authenticated;

create or replace function public.web_push_should_deliver(
  p_user_id uuid,
  p_space_id uuid,
  p_kind text,
  p_stable_key text,
  p_now timestamptz default now()
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  pref record;
begin
  select np.quiet_hours_enabled, np.quiet_hours_start, np.quiet_hours_end, fs.timezone
    into pref
  from public.notification_preferences np
  join public.financial_spaces fs on fs.id = np.space_id
  where np.user_id = p_user_id and np.space_id = p_space_id;

  if not found then return false; end if;

  if p_kind in ('planThreshold','cardLimitThreshold') and p_stable_key ~ ':100$' then
    return true;
  end if;

  return not private.is_web_push_quiet(
    p_now,
    pref.timezone,
    pref.quiet_hours_enabled,
    pref.quiet_hours_start,
    pref.quiet_hours_end
  );
end;
$$;

revoke all on function public.web_push_should_deliver(uuid,uuid,text,text,timestamptz) from public, anon, authenticated;
grant execute on function public.web_push_should_deliver(uuid,uuid,text,text,timestamptz) to service_role;

create or replace function public.get_daily_summary_push_candidates(
  p_now timestamptz default now(),
  p_limit integer default 100
)
returns table(
  user_id uuid,
  space_id uuid,
  stable_key text,
  kind text,
  title text,
  body text,
  route text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  pref record;
  snap record;
  wallet jsonb;
  today_local date;
  scheduled_at timestamptz;
  candidate_key text;
  candidate_body text;
  details text;
  category_attention_count integer;
  card_attention_count integer;
  tomorrow_count integer;
  overdue_count integer;
  emitted integer := 0;
begin
  p_limit := least(greatest(coalesce(p_limit, 100), 1), 500);

  for pref in
    select np.*, fs.timezone
    from public.notification_preferences np
    join public.financial_spaces fs on fs.id = np.space_id
    where np.financial_reminders_enabled
      and np.daily_summary_enabled
      and exists (
        select 1 from public.space_members sm
        where sm.space_id = np.space_id and sm.user_id = np.user_id
      )
      and exists (
        select 1 from public.web_push_subscriptions ws
        where ws.user_id = np.user_id and ws.disabled_at is null
      )
    order by np.updated_at, np.space_id
  loop
    perform set_config('request.jwt.claim.sub', pref.user_id::text, true);
    today_local := (p_now at time zone pref.timezone)::date;
    scheduled_at := (today_local::timestamp + pref.daily_summary_time) at time zone pref.timezone;

    if scheduled_at > p_now then continue; end if;
    if private.is_web_push_quiet(
      p_now, pref.timezone, pref.quiet_hours_enabled,
      pref.quiet_hours_start, pref.quiet_hours_end
    ) then continue; end if;

    candidate_key := 'daily_summary:' || pref.space_id::text || ':' || today_local::text;
    if exists (
      select 1 from public.web_push_delivery_log dl
      where dl.user_id = pref.user_id and dl.stable_key = candidate_key
    ) then continue; end if;

    select * into snap
    from public.get_folego_snapshot(pref.space_id, today_local)
    limit 1;

    select count(*)::integer into category_attention_count
    from public.get_budget_overview(pref.space_id, date_trunc('month', today_local)::date) b
    where b.planned_amount > 0
      and b.budget_source <> 'aggregate'
      and b.usage_ratio >= b.warning_threshold;

    wallet := public.get_wallet_overview(pref.space_id);
    select count(*)::integer into card_attention_count
    from jsonb_array_elements(coalesce(wallet->'cards', '[]'::jsonb)) as c(value)
    where coalesce(nullif(c.value->>'invoice_balance', '')::numeric, 0) > 0
      and coalesce(
        nullif(c.value->>'personal_limit', '')::numeric,
        nullif(c.value->>'issuer_limit', '')::numeric,
        0
      ) > 0
      and (
        coalesce(nullif(c.value->>'invoice_balance', '')::numeric, 0)
        /
        coalesce(
          nullif(c.value->>'personal_limit', '')::numeric,
          nullif(c.value->>'issuer_limit', '')::numeric,
          1
        )
      ) >= 0.70;

    select count(*)::integer into tomorrow_count
    from public.get_upcoming_events(pref.space_id, today_local + 1, today_local + 1, 200) u
    where u.due_date = today_local + 1;

    select count(*)::integer into overdue_count
    from public.get_upcoming_events(pref.space_id, today_local - 30, today_local, 200) u
    where u.overdue;

    candidate_body := private.format_brl(coalesce(snap.spendable_pool, 0))
      || ' livres • '
      || private.format_brl(coalesce(snap.daily_folego, 0))
      || '/dia';

    details := concat_ws(
      ' • ',
      case when category_attention_count > 0 then
        category_attention_count::text || ' ' ||
        case when category_attention_count = 1 then 'categoria em atenção' else 'categorias em atenção' end
      end,
      case when card_attention_count > 0 then
        card_attention_count::text || ' ' ||
        case when card_attention_count = 1 then 'cartão em atenção' else 'cartões em atenção' end
      end,
      case when tomorrow_count > 0 then
        tomorrow_count::text || ' ' ||
        case when tomorrow_count = 1 then 'movimento amanhã' else 'movimentos amanhã' end
      end,
      case when overdue_count > 0 then
        overdue_count::text || ' ' ||
        case when overdue_count = 1 then 'item atrasado' else 'itens atrasados' end
      end
    );

    if coalesce(details, '') <> '' then
      candidate_body := candidate_body || E'\n' || details;
    end if;

    user_id := pref.user_id;
    space_id := pref.space_id;
    stable_key := candidate_key;
    kind := 'dailySummary';
    title := '☀️ Seu Fôlego de hoje';
    body := candidate_body;
    route := '/';
    return next;
    emitted := emitted + 1;
    if emitted >= p_limit then exit; end if;
  end loop;

  perform set_config('request.jwt.claim.sub', '', true);
end;
$$;

revoke all on function public.get_daily_summary_push_candidates(timestamptz,integer) from public, anon, authenticated;
grant execute on function public.get_daily_summary_push_candidates(timestamptz,integer) to service_role;

create or replace function private.baseline_daily_summary_state(
  p_user_id uuid,
  p_space_id uuid default null,
  p_now timestamptz default now()
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  pref record;
  today_local date;
  scheduled_at timestamptz;
  candidate_key text;
begin
  for pref in
    select np.*, fs.timezone
    from public.notification_preferences np
    join public.financial_spaces fs on fs.id = np.space_id
    where np.user_id = p_user_id
      and np.financial_reminders_enabled
      and np.daily_summary_enabled
      and (p_space_id is null or np.space_id = p_space_id)
  loop
    today_local := (p_now at time zone pref.timezone)::date;
    scheduled_at := (today_local::timestamp + pref.daily_summary_time) at time zone pref.timezone;
    if scheduled_at <= p_now then
      candidate_key := 'daily_summary:' || pref.space_id::text || ':' || today_local::text;
      insert into public.web_push_delivery_log(user_id, space_id, stable_key, kind)
      values (pref.user_id, pref.space_id, candidate_key, 'dailySummary')
      on conflict (user_id, stable_key) do nothing;
    end if;
  end loop;
end;
$$;

revoke all on function private.baseline_daily_summary_state(uuid,uuid,timestamptz) from public, anon, authenticated;

create or replace function private.baseline_daily_summary_on_preference_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.daily_summary_enabled and (
    not old.daily_summary_enabled or
    new.daily_summary_time is distinct from old.daily_summary_time
  ) then
    perform private.baseline_daily_summary_state(new.user_id, new.space_id, now());
  end if;
  return new;
end;
$$;

revoke all on function private.baseline_daily_summary_on_preference_change() from public, anon, authenticated;

drop trigger if exists notification_preferences_daily_summary_change_baseline on public.notification_preferences;
create trigger notification_preferences_daily_summary_change_baseline
after update of daily_summary_enabled, daily_summary_time on public.notification_preferences
for each row execute function private.baseline_daily_summary_on_preference_change();

do $$
declare
  existing_job bigint;
begin
  for existing_job in
    select jobid from cron.job where jobname = 'folego-notification-history-retention'
  loop
    perform cron.unschedule(existing_job);
  end loop;
  perform cron.schedule(
    'folego-notification-history-retention',
    '17 3 * * *',
    'delete from public.notification_history where delivered_at < now() - interval ''90 days'';'
  );
end $$;
