-- Web Push delivery for installed PWAs (iOS/iPadOS/desktop).
-- Secrets are intentionally NOT stored in this migration. They live in Supabase Vault.

create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema pg_catalog;

alter table public.notification_preferences
  add column if not exists plan_thresholds_enabled boolean not null default true,
  add column if not exists card_limit_thresholds_enabled boolean not null default true,
  add column if not exists large_expenses_enabled boolean not null default false,
  add column if not exists large_expense_threshold numeric(14,2) not null default 200.00;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'notification_preferences_large_expense_threshold_check'
      and conrelid = 'public.notification_preferences'::regclass
  ) then
    alter table public.notification_preferences
      add constraint notification_preferences_large_expense_threshold_check
      check (large_expense_threshold >= 0);
  end if;
end $$;

create table if not exists public.web_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth_secret text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0,
  disabled_at timestamptz,
  constraint web_push_subscriptions_endpoint_key unique (endpoint)
);

create index if not exists web_push_subscriptions_user_active_idx
  on public.web_push_subscriptions (user_id)
  where disabled_at is null;

alter table public.web_push_subscriptions enable row level security;

drop policy if exists web_push_subscriptions_select_own on public.web_push_subscriptions;
create policy web_push_subscriptions_select_own
on public.web_push_subscriptions for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists web_push_subscriptions_insert_own on public.web_push_subscriptions;
create policy web_push_subscriptions_insert_own
on public.web_push_subscriptions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists web_push_subscriptions_update_own on public.web_push_subscriptions;
create policy web_push_subscriptions_update_own
on public.web_push_subscriptions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists web_push_subscriptions_delete_own on public.web_push_subscriptions;
create policy web_push_subscriptions_delete_own
on public.web_push_subscriptions for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.web_push_delivery_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  space_id uuid references public.financial_spaces(id) on delete cascade,
  stable_key text not null,
  kind text not null,
  sent_at timestamptz not null default now(),
  constraint web_push_delivery_log_user_key unique (user_id, stable_key)
);

create index if not exists web_push_delivery_log_sent_at_idx
  on public.web_push_delivery_log (sent_at);

alter table public.web_push_delivery_log enable row level security;
revoke all on public.web_push_delivery_log from anon, authenticated;

create or replace function public.verify_web_push_cron_token(p_token text)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from vault.decrypted_secrets s
    where s.name = 'folego_web_push_cron_secret'
      and s.decrypted_secret = p_token
  );
$$;

revoke all on function public.verify_web_push_cron_token(text) from public, anon, authenticated;
grant execute on function public.verify_web_push_cron_token(text) to service_role;

create or replace function public.get_web_push_server_config()
returns table(public_key text, private_key text, subject text)
language sql
security definer
set search_path = ''
as $$
  select
    'BH7q2FubEJ5uZqSuZli0usVvqP9dbGyFoGSZu03YDryy_IKuZoVqHzC_9geURT5eNZqmpcAMwYvttD6Pi4zSBiY'::text,
    s.decrypted_secret::text,
    'https://caueccipriano.github.io/folego-app/'::text
  from vault.decrypted_secrets s
  where s.name = 'folego_web_push_vapid_private'
  limit 1;
$$;

revoke all on function public.get_web_push_server_config() from public, anon, authenticated;
grant execute on function public.get_web_push_server_config() to service_role;

create or replace function public.mark_web_push_delivered(
  p_user_id uuid,
  p_space_id uuid,
  p_stable_key text,
  p_kind text
)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.web_push_delivery_log(user_id, space_id, stable_key, kind)
  values (p_user_id, p_space_id, p_stable_key, p_kind)
  on conflict (user_id, stable_key) do nothing;
$$;

revoke all on function public.mark_web_push_delivered(uuid,uuid,text,text) from public, anon, authenticated;
grant execute on function public.mark_web_push_delivered(uuid,uuid,text,text) to service_role;

create or replace function public.get_web_push_candidates(
  p_now timestamptz default now(),
  p_limit integer default 100
)
returns table(
  user_id uuid,
  space_id uuid,
  stable_key text,
  kind text,
  title text,
  body text,
  route text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  pref record;
  evt record;
  budget_row record;
  card_row jsonb;
  wallet jsonb;
  month_start date;
  today_local date;
  planned_at timestamptz;
  lead_days integer;
  entity_type text;
  candidate_kind text;
  candidate_key text;
  candidate_title text;
  candidate_body text;
  candidate_route text;
  ratio numeric;
  threshold_pct integer;
  limit_amount numeric;
  invoice_balance numeric;
  emitted integer := 0;
begin
  p_limit := least(greatest(coalesce(p_limit,100),1),500);

  for pref in
    select np.*, fs.timezone
    from public.notification_preferences np
    join public.financial_spaces fs on fs.id = np.space_id
    where np.financial_reminders_enabled
      and exists (
        select 1
        from public.space_members sm
        where sm.space_id = np.space_id
          and sm.user_id = np.user_id
      )
      and exists (
        select 1
        from public.web_push_subscriptions ws
        where ws.user_id = np.user_id
          and ws.disabled_at is null
      )
  loop
    perform set_config('request.jwt.claim.sub', pref.user_id::text, true);
    today_local := (p_now at time zone pref.timezone)::date;
    month_start := date_trunc('month', today_local)::date;

    -- Scheduled financial reminders.
    for evt in
      select *
      from public.get_upcoming_events(
        pref.space_id,
        today_local - 30,
        today_local + 30,
        200
      )
    loop
      candidate_kind := null;

      if evt.overdue then
        if pref.overdue_enabled then candidate_kind := 'overdue'; end if;
      elsif evt.source = 'invoice' then
        if pref.invoices_enabled then candidate_kind := 'invoice'; end if;
      elsif evt.source = 'debt' then
        if pref.debts_enabled then candidate_kind := 'debtInstallment'; end if;
      elsif evt.source = 'recurring' then
        if evt.direction = 'income' then
          if pref.expected_income_enabled then candidate_kind := 'recurringIncome'; end if;
        elsif evt.navigation_target = 'subscription' then
          if pref.subscriptions_enabled then candidate_kind := 'subscription'; end if;
        elsif pref.recurrences_enabled then
          candidate_kind := 'recurrence';
        end if;
      else
        candidate_kind := 'commitment';
      end if;

      if candidate_kind is null then continue; end if;

      planned_at := ((evt.due_date - pref.reminder_offset_days)::timestamp + pref.preferred_time)
                    at time zone pref.timezone;

      if not evt.overdue and planned_at > p_now then
        continue;
      end if;

      entity_type := case
        when evt.source = 'invoice' then 'invoice'
        when evt.source = 'debt' then 'debt_installment'
        when evt.navigation_target = 'subscription' then 'subscription'
        when evt.source = 'recurring' then 'recurring'
        else evt.source
      end;

      candidate_key := entity_type || ':' || evt.source_id::text || ':' ||
                       evt.due_date::text || ':' || pref.reminder_offset_days::text ||
                       ':' || candidate_kind;

      if exists (
        select 1 from public.web_push_delivery_log dl
        where dl.user_id = pref.user_id and dl.stable_key = candidate_key
      ) then
        continue;
      end if;

      lead_days := greatest(evt.due_date - today_local, 0);
      candidate_title := evt.title;
      candidate_body := case
        when evt.overdue then evt.title || ' está atrasado'
        when evt.direction = 'income' and lead_days = 0 then evt.title || ' está previsto para hoje'
        when evt.direction = 'income' and lead_days = 1 then evt.title || ' está previsto para amanhã'
        when evt.direction = 'income' then evt.title || ' está previsto em ' || lead_days || ' dias'
        when lead_days = 0 then evt.title || ' vence hoje'
        when lead_days = 1 then evt.title || ' vence amanhã'
        else evt.title || ' vence em ' || lead_days || ' dias'
      end;
      candidate_route := case
        when evt.source = 'invoice' and evt.card_id is not null and evt.invoice_id is not null
          then '/wallet/card/' || evt.card_id::text || '/invoice/' || evt.invoice_id::text
        when evt.source = 'debt' and evt.debt_id is not null
          then '/wallet/debt/' || evt.debt_id::text
        when evt.navigation_target = 'subscription'
          then '/transactions/subscriptions/' || evt.source_id::text
        when evt.source = 'recurring'
          then '/transactions/recurring/' || evt.source_id::text
        else '/agenda'
      end;

      user_id := pref.user_id;
      space_id := pref.space_id;
      stable_key := candidate_key;
      kind := candidate_kind;
      title := candidate_title;
      body := candidate_body;
      route := candidate_route;
      return next;
      emitted := emitted + 1;
      if emitted >= p_limit then return; end if;
    end loop;

    -- Budget/category thresholds using the same canonical overview as Plano.
    if pref.plan_thresholds_enabled then
      for budget_row in
        select *
        from public.get_budget_overview(pref.space_id, month_start)
        where planned_amount > 0
          and budget_source <> 'aggregate'
      loop
        ratio := budget_row.usage_ratio;
        threshold_pct := case
          when ratio >= 1 then 100
          when ratio >= budget_row.critical_threshold then round(budget_row.critical_threshold * 100)::int
          when ratio >= budget_row.warning_threshold then round(budget_row.warning_threshold * 100)::int
          else null
        end;
        if threshold_pct is null then continue; end if;

        candidate_key := 'plan:' || budget_row.category_id::text || ':' ||
                         month_start::text || ':' || threshold_pct::text;
        if exists (
          select 1 from public.web_push_delivery_log dl
          where dl.user_id = pref.user_id and dl.stable_key = candidate_key
        ) then continue; end if;

        candidate_kind := 'planThreshold';
        candidate_title := case
          when threshold_pct >= 100 then 'limite de ' || budget_row.category_name || ' atingido'
          else budget_row.category_name || ' chegou a ' || threshold_pct || '%'
        end;
        candidate_body := case
          when threshold_pct >= 100 then 'Você atingiu o limite planejado desta categoria.'
          else 'Você está se aproximando do limite que definiu no Plano.'
        end;
        candidate_route := '/plan';

        user_id := pref.user_id;
        space_id := pref.space_id;
        stable_key := candidate_key;
        kind := candidate_kind;
        title := candidate_title;
        body := candidate_body;
        route := candidate_route;
        return next;
        emitted := emitted + 1;
        if emitted >= p_limit then return; end if;
      end loop;
    end if;

    -- Card thresholds based on the same current invoice balance shown in Carteira.
    if pref.card_limit_thresholds_enabled then
      wallet := public.get_wallet_overview(pref.space_id);
      for card_row in select value from jsonb_array_elements(coalesce(wallet->'cards','[]'::jsonb))
      loop
        limit_amount := coalesce(
          nullif(card_row->>'personal_limit','')::numeric,
          nullif(card_row->>'issuer_limit','')::numeric
        );
        invoice_balance := coalesce(nullif(card_row->>'invoice_balance','')::numeric,0);
        if limit_amount is null or limit_amount <= 0 then continue; end if;

        ratio := invoice_balance / limit_amount;
        threshold_pct := case
          when ratio >= 1 then 100
          when ratio >= .90 then 90
          when ratio >= .70 then 70
          else null
        end;
        if threshold_pct is null then continue; end if;

        candidate_key := 'card:' || (card_row->>'id') || ':' ||
                         month_start::text || ':' || threshold_pct::text;
        if exists (
          select 1 from public.web_push_delivery_log dl
          where dl.user_id = pref.user_id and dl.stable_key = candidate_key
        ) then continue; end if;

        candidate_kind := 'cardLimitThreshold';
        candidate_title := case
          when threshold_pct >= 100 then 'limite do cartão atingido'
          else 'seu cartão chegou a ' || threshold_pct || '% do limite'
        end;
        candidate_body := coalesce(card_row->>'name','Cartão') ||
          case when threshold_pct >= 100
            then ' atingiu o limite definido.'
            else ' está se aproximando do limite definido.'
          end;
        candidate_route := '/wallet';

        user_id := pref.user_id;
        space_id := pref.space_id;
        stable_key := candidate_key;
        kind := candidate_kind;
        title := candidate_title;
        body := candidate_body;
        route := candidate_route;
        return next;
        emitted := emitted + 1;
        if emitted >= p_limit then return; end if;
      end loop;
    end if;

    -- Optional relevant-spend alert. Only recent events are considered to avoid
    -- flooding a user when they enable push for the first time.
    if pref.large_expenses_enabled and pref.large_expense_threshold > 0 then
      for evt in
        select fe.*
        from public.financial_events fe
        where fe.space_id = pref.space_id
          and fe.status = 'confirmed'
          and fe.event_type in ('expense','card_purchase')
          and fe.amount >= pref.large_expense_threshold
          and fe.created_at >= p_now - interval '15 minutes'
        order by fe.created_at
      loop
        candidate_key := 'large_expense:' || evt.id::text;
        if exists (
          select 1 from public.web_push_delivery_log dl
          where dl.user_id = pref.user_id and dl.stable_key = candidate_key
        ) then continue; end if;

        user_id := pref.user_id;
        space_id := pref.space_id;
        stable_key := candidate_key;
        kind := 'largeExpense';
        title := 'gasto relevante registrado';
        body := 'Um gasto acima do valor que você definiu foi registrado no Fôlego.';
        route := '/transactions';
        return next;
        emitted := emitted + 1;
        if emitted >= p_limit then return; end if;
      end loop;
    end if;
  end loop;

  perform set_config('request.jwt.claim.sub', '', true);
end;
$$;

revoke all on function public.get_web_push_candidates(timestamptz,integer) from public, anon, authenticated;
grant execute on function public.get_web_push_candidates(timestamptz,integer) to service_role;

create or replace function private.invoke_folego_web_push_dispatch()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_token text;
begin
  select s.decrypted_secret into v_token
  from vault.decrypted_secrets s
  where s.name = 'folego_web_push_cron_secret'
  limit 1;

  if v_token is null or v_token = '' then
    return;
  end if;

  perform net.http_post(
    url := 'https://ycumrvkwqizlnehelhek.supabase.co/functions/v1/folego-push-dispatch',
    headers := jsonb_build_object('Content-Type','application/json'),
    body := jsonb_build_object('cron_token', v_token),
    timeout_milliseconds := 10000
  );
end;
$$;

revoke all on function private.invoke_folego_web_push_dispatch() from public, anon, authenticated;

do $$
declare
  existing_job bigint;
begin
  for existing_job in
    select jobid from cron.job where jobname = 'folego-web-push-dispatch'
  loop
    perform cron.unschedule(existing_job);
  end loop;

  perform cron.schedule(
    'folego-web-push-dispatch',
    '*/5 * * * *',
    'select private.invoke_folego_web_push_dispatch();'
  );
end $$;
